version: '3'
services:
  db:
    image: postgres:12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    env_file: .env
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug:3.0.1-germanium
    stdin_open: true
    tty: true
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: 2g

volumes:
  bundle:
  node_modules:
